//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlephClicker.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double aleph {
            get {
                return ((double)(this["aleph"]));
            }
            set {
                this["aleph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double upgrade {
            get {
                return ((double)(this["upgrade"]));
            }
            set {
                this["upgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double multiplier {
            get {
                return ((double)(this["multiplier"]));
            }
            set {
                this["multiplier"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ApplicationFirstStart {
            get {
                return ((bool)(this["ApplicationFirstStart"]));
            }
            set {
                this["ApplicationFirstStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool fullscreen {
            get {
                return ((bool)(this["fullscreen"]));
            }
            set {
                this["fullscreen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double click {
            get {
                return ((double)(this["click"]));
            }
            set {
                this["click"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double exp {
            get {
                return ((double)(this["exp"]));
            }
            set {
                this["exp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public double exp_max {
            get {
                return ((double)(this["exp_max"]));
            }
            set {
                this["exp_max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int level {
            get {
                return ((int)(this["level"]));
            }
            set {
                this["level"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph A" +
            "leph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Ale" +
            "ph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph Aleph" +
            " Aleph Aleph Aleph Aleph ")]
        public string aleph_ascii {
            get {
                return ((string)(this["aleph_ascii"]));
            }
            set {
                this["aleph_ascii"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color vis_min {
            get {
                return ((global::System.Drawing.Color)(this["vis_min"]));
            }
            set {
                this["vis_min"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color vis_top {
            get {
                return ((global::System.Drawing.Color)(this["vis_top"]));
            }
            set {
                this["vis_top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AutoClick {
            get {
                return ((double)(this["AutoClick"]));
            }
            set {
                this["AutoClick"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double MilitaryBase {
            get {
                return ((double)(this["MilitaryBase"]));
            }
            set {
                this["MilitaryBase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double Anti_Si_Propaganda {
            get {
                return ((double)(this["Anti_Si_Propaganda"]));
            }
            set {
                this["Anti_Si_Propaganda"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public double clickM_cost {
            get {
                return ((double)(this["clickM_cost"]));
            }
            set {
                this["clickM_cost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public double ac_cost {
            get {
                return ((double)(this["ac_cost"]));
            }
            set {
                this["ac_cost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public double AMB_cost {
            get {
                return ((double)(this["AMB_cost"]));
            }
            set {
                this["AMB_cost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12000")]
        public double ASP_cost {
            get {
                return ((double)(this["ASP_cost"]));
            }
            set {
                this["ASP_cost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Achivement_OurFirstArmy {
            get {
                return ((bool)(this["Achivement_OurFirstArmy"]));
            }
            set {
                this["Achivement_OurFirstArmy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Achivement_ThisIsJustTheBeginning {
            get {
                return ((bool)(this["Achivement_ThisIsJustTheBeginning"]));
            }
            set {
                this["Achivement_ThisIsJustTheBeginning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Achivement_WelcomeToOsu {
            get {
                return ((bool)(this["Achivement_WelcomeToOsu"]));
            }
            set {
                this["Achivement_WelcomeToOsu"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Achivement_AllAchivements {
            get {
                return ((bool)(this["Achivement_AllAchivements"]));
            }
            set {
                this["Achivement_AllAchivements"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int img {
            get {
                return ((int)(this["img"]));
            }
            set {
                this["img"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool changeImage {
            get {
                return ((bool)(this["changeImage"]));
            }
            set {
                this["changeImage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Blue")]
        public global::System.Drawing.Color barColor {
            get {
                return ((global::System.Drawing.Color)(this["barColor"]));
            }
            set {
                this["barColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RGB {
            get {
                return ((bool)(this["RGB"]));
            }
            set {
                this["RGB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool changeColor {
            get {
                return ((bool)(this["changeColor"]));
            }
            set {
                this["changeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public int mp_Volume {
            get {
                return ((int)(this["mp_Volume"]));
            }
            set {
                this["mp_Volume"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Achivement {
            get {
                return ((int)(this["Achivement"]));
            }
            set {
                this["Achivement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Achivment_TheGod {
            get {
                return ((bool)(this["Achivment_TheGod"]));
            }
            set {
                this["Achivment_TheGod"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int Achivement_Max {
            get {
                return ((int)(this["Achivement_Max"]));
            }
            set {
                this["Achivement_Max"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowVIS {
            get {
                return ((bool)(this["ShowVIS"]));
            }
            set {
                this["ShowVIS"] = value;
            }
        }
    }
}
